name: Continuous Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ "published" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Install GitVersion
      uses: GitTools/actions/gitversion/setup@v0.9.14
      with:
        versionSpec: '5.x'
        
    - name: Run GitVersion
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.9.14
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore -p:Version=${{ steps.gitversion.outputs.semVer }}
      
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
      
    - name: Package with NuGet
      if: github.event_name == 'release'
      run: |
        dotnet pack --configuration Release -p:Version=${{ steps.gitversion.outputs.semVer }} -p:RepositoryUrl="https://github.com/tristanlabelle/Pianomino"
        dotnet nuget push "Pianomino.Theory/bin/Release/Pianomino.Theory.${{ steps.gitversion.outputs.semVer }}.nupkg" --api-key ${{secrets.NUGET_ORG_API_KEY}} --source https://api.nuget.org/v3/index.json

